[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DASTRONOMY_ENGINE_WHOLE_SECOND

[env:motor_test]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DASTRONOMY_ENGINE_WHOLE_SECOND
build_src_filter = -<*> +<../test/motor_test.cpp>

[env:motor_test_accel]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<../test/motor_test_accel.cpp>
lib_deps = gin66/FastAccelStepper